
package br.com.fiap.financeira.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastroCliente", targetNamespace = "http://finCliente.com.br", wsdlLocation = "http://54.242.136.113:8080/FinCliente/services/CadastroCliente?wsdl")
public class CadastroCliente
    extends Service
{

    private final static URL CADASTROCLIENTE_WSDL_LOCATION;
    private final static WebServiceException CADASTROCLIENTE_EXCEPTION;
    private final static QName CADASTROCLIENTE_QNAME = new QName("http://finCliente.com.br", "CadastroCliente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.242.136.113:8080/FinCliente/services/CadastroCliente?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTROCLIENTE_WSDL_LOCATION = url;
        CADASTROCLIENTE_EXCEPTION = e;
    }

    public CadastroCliente() {
        super(__getWsdlLocation(), CADASTROCLIENTE_QNAME);
    }

    public CadastroCliente(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTROCLIENTE_QNAME, features);
    }

    public CadastroCliente(URL wsdlLocation) {
        super(wsdlLocation, CADASTROCLIENTE_QNAME);
    }

    public CadastroCliente(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTROCLIENTE_QNAME, features);
    }

    public CadastroCliente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroCliente(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CadastroClientePortType
     */
    @WebEndpoint(name = "CadastroClienteHttpSoap11Endpoint")
    public CadastroClientePortType getCadastroClienteHttpSoap11Endpoint() {
        return super.getPort(new QName("http://finCliente.com.br", "CadastroClienteHttpSoap11Endpoint"), CadastroClientePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroClientePortType
     */
    @WebEndpoint(name = "CadastroClienteHttpSoap11Endpoint")
    public CadastroClientePortType getCadastroClienteHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://finCliente.com.br", "CadastroClienteHttpSoap11Endpoint"), CadastroClientePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTROCLIENTE_EXCEPTION!= null) {
            throw CADASTROCLIENTE_EXCEPTION;
        }
        return CADASTROCLIENTE_WSDL_LOCATION;
    }

}
